const replace_list = {
    "I am ": "I'm ",
    "I don't care ": "IDC ",
    "I don't know ": "IDK",
    "Im ": "I'm ",
    "also known as ": "AKA",
    "altitude ": "alt. ",
    "and ": "& ",
    "anti fascist ": "antifa ",
    "anti fascists ": "antifa ",
    "anti-fascist ": "antifa ",
    "anti-fascists ": "antifa ",
    "apartment ": "apt. ",
    "appointment ": "appt. ",
    "approximately ": "approx. ",
    "as far as I know ": "AFAIK ",
    "as far as I recall ": "AFAIR ",
    "as far as I remember ": "AFAIR ",
    "as fuck ": "AF ",
    "as soon as possible ": "ASAP ",
    "ask me anything ": "AMA",
    "avenue ": "Ave. ",
    "back the fuck off ": "BTFO ",
    "be right back ": "BRB ",
    "behind the scenes ": "BTS ",
    "black lives matter ": "BLM ",
    "blown the fuck out ": "BTFO ",
    "boulevard ": "Blvd. ",
    "by the way ": "BTW ",
    "can not ": "can't ",
    "cannot ": "can't ",
    "department ": "dept. ",
    "did you know ": "DYK ",
    "direct message ": "DM ",
    "do it yourself ": "DIY ",
    "do not ": "don't ",
    "don't give a fuck ": "DGAF ",
    "dont ": "don't ",
    "established ": "est. ",
    "estimated time of arrival ": "ETA ",
    "facebook ": "FB ",
    "for the win ": "FTW ",
    "for your Information ": "FYI ",
    "frequently asked question ": "FAQ ",
    "fuck the world ": "FTW ",
    "get the fuck out ": "GTFO ",
    "i ": "I ",
    "i'm ": "I'm ",
    "in before ": "INB4 ",
    "in case you didn't know ": "ICYDK ",
    "in case you missed it ": "ICYMI ",
    "in my honest opinion ": "IMHO ",
    "in my opinion ": "IMO ",
    "in real life ": "IRL ",
    "instagram ": "IG ",
    "is not ": "isn't ",
    "it is ": "it's ",
    "let me know ": "LMK ",
    "life pro tip ": "LPT ",
    "life pro-tip ": "LPT ",
    "maximum ": "max. ",
    "minimum ": "min. ",
    "minute ": "min. ",
    "miscellaneous ": "misc. ",
    "mister ": "Mr. ",
    "mistress ": "Mrs. ",
    "never mind ": "NVM ",
    "nevermind ": "NVM ",
    "no big deal ": "NBD ",
    "not available ": "N/A ",
    "not safe for work ": "NSFW ",
    "oh my God ": "OMG ",
    "original post ": "OP ",
    "original poster ": "OP ",
    "over-time ": "OT ",
    "overtime ": "OT ",
    "payed time off ": "PTO ",
    "people of color ": "POC ",
    "plus ": "+ ",
    "point of view ": "POV ",
    "police department ": "PD ",
    "police dept ": "PD ",
    "police dept. ": "PD ",
    "prime minister ": "PM ",
    "private message ": "PM ",
    "take your time ": "TYT ",
    "telephone ": "tel. ",
    "temperature ": "temp. ",
    "to be decided ": "TBD ",
    "to be determined ": "TBD ",
    "to much information ": "TMI ",
    "versus ": "vs. ",
    "veteran ": "vet. ",
    "was not ": "wasn't ",
    "word of mouth ": "WOM ",
    "work in progress ": "WIP ",
    "would have ": "would've ",
    "you ": "you ",
    "you are ": "you're ",
    "youtube ": "YT ",
}
