const replace_list = {
    "I am ": "I'm ",
    "I don't care ": "IDC ",
    "I don't know ": "IDK",
    "Im ": "I'm ",
    "also known as ": "AKA",
    "altitude ": "alt. ",
    "and ": "& ",
    "apartment ": "apt. ",
    "appointment ": "appt. ",
    "approximately ": "approx. ",
    "as far as I know ": "AFAIK ",
    "as far as I recall ": "AFAIR ",
    "as far as I remember ": "AFAIR ",
    "as soon as possible ": "ASAP ",
    "ask me anything ": "AMA",
    "avenue ": "Ave. ",
    "be right back ": "BRB ",
    "boulevard ": "Blvd. ",
    "can not ": "can't ",
    "cannot ": "can't ",
    "department ": "dept. ",
    "do it yourself ": "DIY ",
    "do not ": "don't ",
    "dont ": "don't ",
    "established ": "est. ",
    "estimated time of arrival ": "ETA ",
    "for the win ": "FTW ",
    "for your Information ": "FYI ",
    "frequently asked question ": "FAQ ",
    "fuck the world ": "FTW ",
    "i ": "I ",
    "i'm ": "I'm ",
    "in before ": "INB4 ",
    "in my opinion ": "IMO ",
    "in real life ": "IRL ",
    "is not ": "isn't ",
    "it is ": "it's ",
    "maximum ": "max. ",
    "minimum ": "min. ",
    "minute ": "min. ",
    "miscellaneous ": "misc. ",
    "mister ": "Mr. ",
    "mistress ": "Mrs. ",
    "never mind ": "NVM ",
    "nevermind ": "NVM ",
    "not available ": "N/A ",
    "oh my God ": "OMG ",
    "original post ": "OP ",
    "original poster ": "OP ",
    "people of color ": "POC ",
    "plus ": "+ ",
    "point of view ": "POV ",
    "take your time ": "TYT ",
    "telephone ": "tel. ",
    "temperature ": "temp. ",
    "versus ": "vs. ",
    "veteran ": "vet. ",
    "was not ": "wasn't ",
    "work in progress ": "WIP ",
    "would have ": "would've ",
    "you ": "you ",
    "you are ": "you're ",
}
