const replace_list = {
    "avenue": "ave",
    "and ": "& ",
    "can not ": "can't ",
    "cannot ": "can't ",
    "do not ": "don't ",
    "is not ": "isn't ",
    "it is ": "it's ",
    "never mind ": "NVM ",
    "nevermind ": "NVM ",
    "plus ": "+ ",
    "was not ": "wasn't ",
    "work in progress ": "WIP ",
    "would have ": "would've ",
    "you are ": "you're ",
}
