const replace_list = {
    "also known as ": "AKA",
    "and ": "& ",
    "as far as I know ": "AFAIK ",
    "as far as I recall ": "AFAIR ",
    "as far as I remember ": "AFAIR ",
    "ask me anything ": "AMA",
    "avenue": "ave",
    "can not ": "can't ",
    "cannot ": "can't ",
    "do not ": "don't ",
    "for the win ": "FTW ",
    "for your Information ": "FYI ",
    "frequently asked question ": "FAQ ",
    "fuck the world ": "FTW ",
    "i don't know ": "IDK",
    "in my opinion ": "IMO ",
    "in real life ": "IRL ",
    "is not ": "isn't ",
    "it is ": "it's ",
    "never mind ": "NVM ",
    "nevermind ": "NVM ",
    "not available ": "N/A ",
    "oh my God ": "OMG ",
    "original post ": "OP ",
    "original poster ": "OP ",
    "plus ": "+ ",
    "point of view ": "POV ",
    "take your time ": "TYT ",
    "was not ": "wasn't ",
    "work in progress ": "WIP ",
    "would have ": "would've ",
    "you are ": "you're ",
    "i don't care ": "IDC ",
    "i dont care ": "IDC ",
}
